# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffc03fd91aba00393e0657fb8c0404413ad457afb2c49e957a2be40b6061381b1c649817908af66b7e89006779696ee623c1b2c38d53376c3cfb9c4f9950843c

test:
  secret_key_base: 7b7277c7ce38fa39222f0ad4970ec16ee130423bbcf3dec688364893eea23a56f7bde6e7d5873ad1d9c942d5ecf81e43f40adfaec6731559491c5e4d544e82c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
